#+author: conao3
#+date: <2019-01-31 Thu>

[[https://github.com/conao3/docker-jq][https://raw.githubusercontent.com/conao3/files/master/blob/headers/png/docker-jq.png]]
[[https://github.com/conao3/docker-jq/blob/master/LICENSE][https://img.shields.io/github/license/conao3/docker-jq.svg?style=flat-square]]
[[https://github.com/conao3/docker-jq/releases][https://img.shields.io/github/tag/conao3/docker-jq.svg?style=flat-square]]
[[https://github.com/conao3/docker-jq/actions][https://img.shields.io/github/actions/workflow/status/conao3/docker-jq/build.yml?style=flat-square]]
[[https://twitter.com/conao_3][https://img.shields.io/badge/twitter-@conao__3-blue.svg?logo=twitter&style=flat-square]]
[[https://conao3-support.slack.com/join/shared_invite/zt-s6tzyo92-PtRMJYAZBfcC7O5~ZQ0JRQ][https://img.shields.io/badge/chat-on_slack-blue.svg?logo=slack&style=flat-square]]

* Table of Contents
- [[#description][Description]]
- [[#requirements][Requirements]]
- [[#usage][Usage]]
- [[#available-versions][Available Versions]]
- [[#contributing][Contributing]]
- [[#license][License]]

* Description
A containerized version of [[https://github.com/stedolan/jq][jq]], the lightweight and flexible command-line JSON processor.

This Docker image provides a simple way to run specific versions of jq without installing it directly on your system.

* Requirements
Docker must be installed on your system.

#+begin_src bash
  # macOS
  brew install --cask docker

  # Verify installation
  docker version
#+end_src

* Usage
Run jq through Docker:

#+begin_src bash
  echo '{"version":100}' | docker container run -i --rm conao3/jq:1.6 '.version'
  # Output: 100
#+end_src

For convenience, create an alias:

#+begin_src bash
  alias jq='docker container run -i --rm conao3/jq:1.6'
  echo '{"version":100}' | jq '.version'
  # Output: 100
#+end_src

* Available Versions
| Version | Status    |
|---------+-----------|
| 1.6     | Supported |
| 1.5     | Supported |
| 1.4     | Legacy    |
| 1.3     | Legacy    |

Note: Versions 1.3 and 1.4 may have compatibility issues.

* Contributing
Contributions are welcome. Feel free to open issues or submit pull requests.

For discussions, join the [[https://conao3-support.slack.com/join/shared_invite/zt-s6tzyo92-PtRMJYAZBfcC7O5~ZQ0JRQ][Slack community]].

* License
AGPL-3.0. See [[https://github.com/conao3/docker-jq/blob/master/LICENSE][LICENSE]] for details.

Copyright (c) Naoya Yamashita ([[https://github.com/conao3][conao3]])
